# Generated by Django 4.1.7 on 2023-04-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temparature_measurements', models.CharField(max_length=200)),
                ('date_time_now_measurements', models.DateTimeField(auto_now=True)),
                ('date_time_now_add_measurements', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
