# Generated by Django 4.1.7 on 2023-04-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperaturemeasurement',
            name='date_time_now_add_measurements',
        ),
    ]
