# Generated by Django 4.1.7 on 2023-04-25 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_remove_temperaturemeasurement_date_time_now_add_measurements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperaturemeasurement',
            name='date_time_now_measurements',
        ),
        migrations.AddField(
            model_name='temperaturemeasurement',
            name='date_time_now_add_measurements',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
