# Generated by Django 4.1.7 on 2023-04-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_remove_temperaturemeasurement_date_time_now_measurements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturemeasurement',
            name='temparature_measurements',
            field=models.FloatField(),
        ),
    ]
